description: Project memories already exist, use them as needed
prompt: |
  You have access to existing project memories that contain information about this project.
  Read a list of available memories using the `list_memories` tool before proceeding with the task.
  You don't need to read the actual memories, just remember that they exist and that you can read them later if they are relevant for your task.
excluded_tools: []
